### ISSUE TITLE
floating doesn't work on Y axis

### ISSUE THREAD

**Issue by hannesa2** [dbof10/float-keyboard#4]
The example has a major issue: it doesn't work properly !

It can't move on Y axis.
Do you have any clue how to solve it ?

![FloatingKeyboard](https://user-images.githubusercontent.com/3314607/73548286-c9a74600-4440-11ea-93b1-ec722a0a7059.gif)

Yes, you mentioned `centerYBound` and I played around, but fortuneteller without success

**Comment by dbof10** [comment]
the idea is you can play round with `onComputeInsets` inside the service and KeyboardDragDelegate. This is just a proofconcept project to make me believe that the keyboard can float. I used to make it work on a prod project the keyboard can move around the screen

**Comment by dbof10** [comment]
hi @hannesa2 does it work for you now?

**Comment by hannesa2** [comment]
For me it doesn't work and there is no working example. 😞 
But using the keyboard in full screen is promising
